version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ledger_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ledger-network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - ledger-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://user:password@postgres:5432/ledger_db
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      - postgres
      - rabbitmq
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - ledger-network
    command: >
      sh -c "npx prisma migrate deploy && npm run start:prod"

volumes:
  postgres_data:

networks:
  ledger-network:
    driver: bridge